### ISSUE TITLE
Hallow's Treat bot is semi-frozen. 

### ISSUE THREAD

**Issue by zhymmy** [thekwitt/Hallowstreat_Year_3#1]
The bot (in multiple servers) is posting candy drops and boss battles, but all interactions are failing. None of the commands are responding either. 

It's possible I broke it somehow, I renamed the bot in one server for fun, and this started very shortly after. I put the nickname back, but it's still stuck. 

Hopefully you can see this and help us out. Thanks!!

**Comment by thekwitt** [comment]
Thanks for your issue post!

The cloudflare part of the bot connecting to both the Patreon API and the Internal API had some issues with the migration.

Renaming the bot won't ever break the bot's functionality it was just a coincidence funny enough those two lined up!

**Comment by zhymmy** [comment]
Thanks! I was gonna be super impressed if I broke it *everywhere* from that, lol!

**Comment by zhymmy** [comment]
Closing gig.

**Comment by zhymmy** [comment]
If i can do it right anyway
